### PR TITLE
[interactor] logging improvements

### PR DESCRIPTION
**Pull request by delfick**
Remove the generic tornado access logs and introduce a log for valid
commands and all responses

Also introducing a X-Request-Id header that is injected into every
request so that logs may use that request id to be traced to each other.

fixeds #54 

@Djelibeybi you able to take a look and tell me what you think ? thanks

Screen Shot 2021-04-14 at 10 23 22 am

### CODE REVIEW

**Comment by Djelibeybi** [comment]
Yep, updating my local container with this branch now.

**Comment by Djelibeybi** [comment]
My initial thought is that outputting the entire JSON body (especially for the larger bodies like a transform or animation) may be too much for this sort of log.  Also, `method` and `path` are static for all requests so there's no need to log it for Interactor. 

The items I would most want to see in the logs are: command, matcher, remote_ip, took_seconds.

 If there were a way to create a seperate log of json bodies/responses that could be enabled for testing/debugging purpsoes, that would be super peachy keen. Especially if you could save them by request_identifier so that it could be tracked back to the logs.

**Comment by delfick** [comment]
Fair enough. The full body can indeed be too much. What I might do is include just matcher and leave out everything else. A real solution is configuration but I don't have time sorry. Same with more granular logging options.

For debugging I'd suggest running through [ngrok](https://ngrok.com/) and using it's inspector.

**Comment by delfick** [comment]
and I'll leave path and method as it's not harmful and you can access these via websockets. Though you don't really get Response logs from websockets, but I'll deal with that another day

I think what I have here is good enough within the constraints of what time I have

**Comment by Djelibeybi** [comment]
Those are all excellent points I'm happy to concede. :)

**Comment by delfick** [comment]
Thanks, sorry I can't do more.

**Comment by Djelibeybi** [comment]
Aboslutely nothing to be sorry about, this is more than I expected! I'm very happy (moreso now that I've learned about ngrok).

**Comment by delfick** [comment]
yeah, ngrok is great :)

**Pull request merged**
