### PR TITLE
[interactor] add commands to control tile animations

### PR DESCRIPTION
**Pull request by delfick**
Adding the following commands

* animation/start
* animation/pause
* animation/resume
* animation/stop
* animation/info
* animation/help

They should do what you expect :)

### CODE REVIEW

**Comment by Djelibeybi** [comment]
This is awesome. I’ll write up a blog post on how to create a HomeKit switch to turn on and off Tile effects using Interactor when I’m back home next week.

**Comment by delfick** [comment]
:)

**Comment by Final-Hawk** [comment]
Great work @delfick, thanks for the release

**Comment by Djelibeybi** [comment]
Is there a way to use `lifx lan:arrange` and provide that arrangement for Interactor?

**Comment by delfick** [comment]
I'd prefer keeping them as separate. Especially since for now that means
interactor has no javascript tooling.

**Comment by Djelibeybi** [comment]
Yeah, I'm happy with them being seperate, I'm just not sure where Arranger stores its arrangements. So if I use `lifx lan:arrange` on my desktop, how do I ensure that Interactor running in a container on my NAS uses the same arrangement?

**Comment by delfick** [comment]
The arranger is changing user_x/user_y properties on the tiles themselves.
A tile animation will read these values when the device is first discovered
and assume they don't change. So if you change those, then you need to
restart the animation and it'll work.

**Comment by Final-Hawk** [comment]
Oh so the tile arranger on the Pi is not locally stored, it sends the arrangement to the tiles and the tiles store that data.

**Comment by delfick** [comment]
yeap :)

**Comment by Djelibeybi** [comment]
Perfect! I have taken it for a brief spin and it works as expected. :) I'll probably write something up proper later this week or next week.

**Comment by delfick** [comment]
thanks :)

**Comment by Final-Hawk** [comment]
> I'll probably write something up proper later this week or next week.

Can you post the link when it's done? Thanks

**Pull request merged**
