### PR TITLE
[interactor] Better graceful shutdown

### LINKED ISSUE #41: RFE: Need to way to tell Interactor to stop gracefully
Currently, the only way to stop `lifx lan:interactor` is by killing the process, which makes `systemd` rather cross about the whole situation and renders `Restart=on-failure` a bit hit and miss. 

It would be good if the `status` command took an optional boolean parameter `shutdown` and if that parameter is `true`, Interactor would shut itself down.

I'd add this myself, but I don't know how to tell Interactor to end. 😂

### PR DESCRIPTION
**Pull request by delfick**
fixes #41

Though I'm gonna think about this some more, what I have here works but
I think I can make this better

And I need unit tests and to play with it some more and also I'm
changing core photons here

### CODE REVIEW

**Comment by Djelibeybi** [comment]
Is the idea to still send a `SIGTERM` to the running process, just handle it better? Because I don't see a way to trigger the shutdown from a Interactor command.

**Comment by delfick** [comment]
ah, yes, I should add that too.

But yes, I want to make sigterm actually be graceful, cause currently it very much isn't

This file will never be done lol : 
https://github.com/delfick/photons/commits/main/modules/photons_app/runner.py
https://github.com/delfick/photons/commits/fcd7466c5ae29335e0675ac69559001b9adcf365/photons_app/runner.py

It's very complicated.

I have an idea I'll start working on to make it better though.

**Comment by Djelibeybi** [comment]
I’m glad you think it’s complicated too  😁

**Comment by delfick** [comment]
hehhehehe

**Comment by delfick** [comment]
Fixed better in #48

**Pull request closed without merging**
