### PR TITLE
deps: bump lru-dict version to match Home Assistant's minimum required version

### PR DESCRIPTION
**Pull request by Djelibeybi**
Signed-off-by: Avi Miller <me@dje.li>

### CODE REVIEW

**Comment by Djelibeybi** [comment]
Currently it's not possible to install Photons into a Home Assistant venv while maintaining depedency checks.

**Review by delfick — APPROVED** [review]

**Comment by delfick** [comment]
do you want me to release a new version with this change?

**Comment by Djelibeybi** [comment]
If it's not too much bother, that would be super peachy keen.

**Comment by delfick** [comment]
0.42.7 has been released :)

**Pull request merged**
