### PR TITLE
[packaging] adding a LICENSE to the packages on pypi

### LINKED ISSUE #34: The tarballs on PyPi are missing a LICENSE file
Motivated by #33, I've been noodling with creating RPMs for Photons, mostly as a excuse to refresh my knowledge on RPM packaging and it's ... _nuances_. 

As part of that exercise, I noticed that the source tarballs hosted on PyPi do not contain the `LICENSE` file. It would probably be a good idea to include one. 😄

### PR DESCRIPTION
**Pull request by delfick**
Fixes #34

Anything else you need to make the rpm @Djelibeybi  ?

### CODE REVIEW

**Comment by Djelibeybi** [comment]
I'll need to package https://github.com/delfick/delfick_project as well, so it's probably worth checking that it has a `LICENSE` file too. Besides that, I'll let you know as I get further along. I'm having to learn all the changes to Fedora's packaging guidelines (might as well do it proper) which is both fun and time-consuming.

**Comment by Djelibeybi** [comment]
I've just found another one: for some reason, the tarball on PyPi has a `lifx_photons_core.egg-info` directory (with underscores) but I can't determine why. It _should_ be `lidx-photons-core` with hyphens to match the name of the package.

**Comment by delfick** [comment]
ok, I'll add it to delfick_project too. As for egg-info, it seems that's just what it does. Does it cause problems?

**Comment by Djelibeybi** [comment]
Nope. I've found another package that includes a hyphen and it's handled in the RPM specification file. [This particular] crisis averted! 😉

**Comment by delfick** [comment]
hehehhe, also, https://www.python.org/dev/peps/pep-0426/#name `All comparisons of distribution names MUST be case insensitive, and MUST consider hyphens and underscores to be equivalent.`

**Comment by delfick** [comment]
delfick_project 0.7.8 now has LICENSE in the pypi package. Next version of Photons will want it

**Pull request merged**
