### PR TITLE
[interactor] creating a docker image for home assistant

### PR DESCRIPTION
**Pull request by delfick**
I have no experience with using home assistant or the time to investigate that, so I might need help making the docs useful.

### CODE REVIEW

**Comment by delfick** [comment]
@Djelibeybi @Final-Hawk  :)

**Comment by Final-Hawk** [comment]
Looks good! Great Job!

**Review by Final-Hawk — CHANGES_REQUESTED** [review]
change pacman to lights_red, just so when calling command it is labeled appropriately for this example

**Comment by delfick** [comment]
good point. Fixed. I'll probs have time to merge in the evening.

**Pull request merged**
