### PR TITLE
Rearranging the container image build steps to reduce image size

### PR DESCRIPTION
**Pull request by Djelibeybi**
This change should also remove the need to squash the final image as I've merged the two `RUN` directives into one.

Signed-off-by: Avi Miller <me@dje.li>

### CODE REVIEW

**Comment by Djelibeybi** [comment]
Resolves #22 (hopefully).

**Comment by delfick** [comment]
Looks good 👍 

One small nit, can you remake the commit message

```
[interactor] reduce docker image size

Made it so the gcc dependency is temporary just to when we install the
interactor into the virtualenv
```

Thanks :)

https://gist.github.com/matthewhudson/1475276

**Comment by Djelibeybi** [comment]
Commit message updated as requested.

**Comment by delfick** [comment]
fantastic!

I'll merge and retag later :)

**Comment by Djelibeybi** [comment]
If possible, it would be great if you could remind me of the steps to get Harpoon to build the image itself. I'd like to do a sanity test (now that I'm thinking about it) before the merge, but I can't find my notes on how to make Harpoon do what it needs to do.

**Comment by delfick** [comment]
`./apps/interactor/docker/harpoon run lifx-photons-interactor`

(to just build, say `make` instead of `run`)

I'll wait for your sanity check before merging then :)

**Comment by Djelibeybi** [comment]
(There is no `build` command for Harpoon, so I used `run` instead). Sanity check looks good:

```
djelibeybi/lifx-photons-interactor    latest              5ff4e77159fb        40 seconds ago      244MB
delfick/lifx-photons-interactor       latest              ba8e8a125467        4 weeks ago         357MB
```

The image size is reduced by 113MB with this change.

**Comment by delfick** [comment]
`make` rather than `build`

**Comment by delfick** [comment]
did you edit harpoon.yml to say `djelibeybi` instead of `delfick` for that ?

**Comment by delfick** [comment]
(that only matters for push, but it does use it to tag the image locally as well)

**Comment by Djelibeybi** [comment]
> (that only matters for push, but it does use it to tag the image locally as well)

Correct. I wanted it not to overwrite the upstream image so that I could compare. :) `make` worked fine, same results.

**Comment by delfick** [comment]
good point :)

**Comment by delfick** [comment]
https://travis-ci.org/github/delfick/photons/builds/729170787

**Pull request merged**
