### PR TITLE
[ci] better github action for creating interactor docker image

### PR DESCRIPTION
**Pull request by delfick**
Well that was offensively easy.

https://github.com/delfick/photons/runs/1639086910?check_suite_focus=true

Thanks @Djelibeybi for the suggestion

### CODE REVIEW

**Comment by Djelibeybi** [comment]
It was almost... too easy. 😂 My next suggestion is to publish the container image to the [GitHub Container Registry](https://docs.github.com/en/free-pro-team@latest/packages/guides/enabling-improved-container-support) as well as the Docker Hub.

**Comment by delfick** [comment]
oh yeah. another day :)

**Comment by Djelibeybi** [comment]
You said that about switching actions, so 🤷‍♀️

**Comment by delfick** [comment]
hahhaha, I've run out of weekend.

**Pull request merged**
