### PR TITLE
[CI] migrate to github actions

### PR DESCRIPTION
**Pull request by delfick**

### CODE REVIEW

**Comment by delfick** [comment]
hmmm, maybe github actions doesn't run the action defined on the PR itself?

**Comment by Djelibeybi** [comment]
Not until it's merged, no. :)

**Comment by delfick** [comment]
well that's just silly, how am I meant to iterate with that?!

**Comment by Djelibeybi** [comment]
I tend to test GitHub Actions in a private repo copy so no-one sees how long it takes me. :)

**Comment by delfick** [comment]
this seems what I want https://github.com/nektos/act

**Comment by Djelibeybi** [comment]
> this seems what I want https://github.com/nektos/act

... and starred. Nice find.

**Comment by delfick** [comment]
actually, nope it's running on this.

I had a symlink to the workflows folder cause my editor hides the .github folder and it was getting confused

**Comment by delfick** [comment]
There we go, 25 iterations over an hour, got the tests to run :)

Wasted a bunch of time getting it to run on windows. Turns out the tests don't pass on windows anyway, I'll fix that another day.

Will continue this a bit later and get the docker image creation in here too

**Comment by Djelibeybi** [comment]
Docker have a [`build-and-push-docker-image`](https://github.com/marketplace/actions/build-and-push-docker-images) action that uses `buildx`. It would replace the cludgy workaround we had to use with Travis.

**Comment by delfick** [comment]
oh yeah, will have a look sometime

**Pull request merged**
